{% set name = "scmdata" %}
{% set version = "0.16.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 02038d4b1ce68abfecfe729eacde1444f78de58ec8a71bd2b721454a7bee9ec3

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  build:
    - pip
    - python
    - poetry
  host:
    - pip
    - python {{ python_min }}
    - poetry
  run:
    - python >={{ python_min }}
    - cftime
    - numpy
    - openscm-units
    - packaging
    - pandas >=1.1
    - pint
    - pint-pandas
    - python-dateutil
    - six
    - tqdm
    - xarray
    - importlib-metadata
    - typing-extensions

test:
  requires:
    - python {{ python_min }}
  imports:
    - scmdata

  commands: python -c "import scmdata; assert scmdata.__version__ == '{{ version }}', scmdata.__version__"

about:
  home: https://github.com/openscm/scmdata
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Handling of simple climate model data (part of the OpenSCM project)
  doc_url: https://scmdata.readthedocs.io/en/latest/scmdata
  dev_url: https://github.com/openscm/scmdata

extra:
  recipe-maintainers:
    - znicholls
    - lewisjared
