{% set name = "scmdata" %}
{% set version = "0.2.2" %}

package:
  name: "{{ name|lower }}"
  version: {{ version }}

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "e7f5b1fb5dfd3e563b863c455e1851584338fdbc863bee3deb46431e803f7ab8"

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - numpy
    - scipy
    - pandas
    - pint
    - python-dateutil

test:
  imports:
    - scmdata

  commands:
    python -c "import scmdata; assert scmdata.__version__ == '{{ version }}'"

about:
  home: https://github.com/lewisjared/scmdata
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Handling of Simple Climate Model data
  doc_url: https://scmdata.readthedocs.io/en/latest/scmdata
  dev_url: https://github.com/lewisjared/scmdata

extra:
  recipe-maintainers:
    - znicholls
    - lewisjared
