{% set name = "scmdata" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3fe4825e992ecd41347fe074c280db4e334e8f9a9a864b0537426905ce118453

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - cftime
    - numpy
    - openscm-units
    - packaging
    - pandas >=1.0.4
    - pint-pandas
    - python-dateutil
    - six
    - tqdm
    - xarray

test:
  imports:
    - scmdata

  commands: python -c "import scmdata; assert scmdata.__version__ == '{{ version }}'"

about:
  home: https://github.com/openscm/scmdata
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Handling of simple climate model data (part of the OpenSCM project)
  doc_url: https://scmdata.readthedocs.io/en/latest/scmdata
  dev_url: https://github.com/openscm/scmdata

extra:
  recipe-maintainers:
    - znicholls
    - lewisjared
