travis:
  secure:
    BINSTAR_TOKEN: eZKmvNAdS1mAx/E0DHDWavucQCm8vhALIurSKVXuOA5iEwcD4E7ERFo+M9Ko2nHM0Fa3l3MVfVeWJtGk6aB91BxeYO8iPD75nrSgL78vifHluroe+El3YBdIkDUmqP5elfrywPuyA9/A9yFfFUjgszEi6uiOrDg8DtF4DEVyqyXOXYjd2jOc1OWZ8H4YlcKjGalEl1cDuh6pRR/TXi/3RoFcuLlubQquVEGr8bd0HfcTdePZkTUO/DrE6wBb12aYhguVnDlFCL5H2VieYRNQfTBYD94RTW7KgIY7yTn6xD+cVRWKyTtuyLV3MjDuQ8F/vmhGkcVVmJ3oQqBK/8hNJ9uT659XYIIIuDJeRaLhqTR4G4fg/OwKScza9No7GhF0Q7gXRlO5FNB6HeyA5nYlN9yTCtgicSUOyVd7z5O9gZ/Q25Kfvh6Sgyv7kqzvxkcrXxRUuuMDbuwl++yrHJM9Q0kUzUJHR8tLHxKE2OKNH7tsNzMEEE0nHs8sJnq21iv9NwAwIM/mPkylFZa57zC/uawAdpwDAfm64E+WqcJnw3F2jnLpx7T4RPzcGF9G1ucvhf0j0f/u4Ije+91jdOsXxKhEREetlCRrdHFmB//Vh/FiUsQ3dsrfsb/QFwFTlzM3SHBlrzi4NWWPbomNQF6j6BFbR9nVhzh8jxK6ijNJLbs=
conda_forge_output_validation: true
bot:
  automerge: true
